package chatClient;

import chatLogic.Contacto;
import chatLogic.Mensajes;
import java.awt.Color;
import chatLogic.ServiceUsuariosContactos;
import chatXML.ChatXML;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
public class View extends javax.swing.JFrame implements java.util.Observer {

    /**
     * Creates new form PersonaView
     */
    public View() {
        initComponents();
        getRootPane().setDefaultButton(post);
    }
    String receptor = " ";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoFld = new javax.swing.ButtonGroup();
        bodyPanel = new javax.swing.JPanel();
        mensaje = new javax.swing.JTextField();
        post = new javax.swing.JButton();
        messages = new java.awt.TextArea();
        logout = new javax.swing.JButton();
        BotonInsertar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        textBuscar = new javax.swing.JTextField();
        botonRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Contactos = new javax.swing.JTable();
        Destinatario = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        clave = new javax.swing.JPasswordField();
        finish = new javax.swing.JButton();
        PanelInsercion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textID = new javax.swing.JTextField();
        BotonAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CHAT");

        bodyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bodyPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                bodyPanelComponentShown(evt);
            }
        });

        post.setText("Enviar");
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        BotonInsertar.setText("Insertar contacto");
        BotonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsertarActionPerformed(evt);
            }
        });

        jLabel5.setText("CONTACTOS");

        botonBuscar.setText("Buscar por nombre");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonRefresh.setText("Refresh");
        botonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefreshActionPerformed(evt);
            }
        });

        Contactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        Contactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Contactos);

        Destinatario.setText("Sin destinatario");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messages, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(post))
                    .addComponent(Destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textBuscar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logout)
                            .addComponent(BotonInsertar)
                            .addComponent(Destinatario))
                        .addGap(18, 18, 18)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonRefresh)
                            .addComponent(botonBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(messages, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(post))
                        .addGap(30, 30, 30))))
        );

        loginPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Usuario");

        jLabel2.setText("Clave");

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        finish.setText("Terminar");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login)
                .addGap(102, 102, 102)
                .addComponent(finish)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(finish))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Nombre:");

        jLabel4.setText("Identificacion:");

        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInsercionLayout = new javax.swing.GroupLayout(PanelInsercion);
        PanelInsercion.setLayout(PanelInsercionLayout);
        PanelInsercionLayout.setHorizontalGroup(
            PanelInsercionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInsercionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInsercionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelInsercionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNombre)
                    .addComponent(textID, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelInsercionLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(BotonAgregar)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        PanelInsercionLayout.setVerticalGroup(
            PanelInsercionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInsercionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInsercionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(PanelInsercionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAgregar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bodyPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(PanelInsercion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelInsercion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
        controller.post();
    }//GEN-LAST:event_postActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        id.setBackground(Color.white);
        clave.setBackground(Color.white);
        try {
            controller.login();
            id.setText("");
            clave.setText("");
            ChatXML xml = new ChatXML();
        try {
            ServiceUsuariosContactos.instance().setContactos(xml.cargarContactosXML(model.currentUser).getContactos());
        } catch (JAXBException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
        } catch (Exception ex) {
            id.setBackground(Color.orange);
            clave.setBackground(Color.orange);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        chatXML.ChatXML xml = new ChatXML();
        try {
            xml.crearContactosXML(ServiceUsuariosContactos.instance(),model.currentUser);
            xml.crearMensajesXML(model.getMessages() ,model.getCurrentUser());
        } catch (JAXBException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        this.setTitle(" Desconectado");
        ServiceUsuariosContactos.instance().setInstance();
        controller.logout();
        
    }//GEN-LAST:event_logoutActionPerformed

    
    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        System.exit(0);
    }//GEN-LAST:event_finishActionPerformed

    private void BotonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsertarActionPerformed
        this.loginPanel.setVisible(false);
        this.bodyPanel.setVisible(false);
        this.PanelInsercion.setVisible(true);
    }//GEN-LAST:event_BotonInsertarActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
         
        if(this.textID.getText().isEmpty()||this.textNombre.getText().isEmpty())return;
        Contacto c1 = new Contacto(this.textNombre.getText(),this.textID.getText());
        ServiceUsuariosContactos.instance().add(c1);
        this.textID.setText("");
        this.textNombre.setText("");
        this.loginPanel.setVisible(false);
        this.bodyPanel.setVisible(true);
        this.PanelInsercion.setVisible(false);
//        int pos =Contactos.getSelectedRow();
        boolean bandera = false;
        receptor=c1.getId();
        if(this.model.getMessages()==null){
            Mensajes ms = new Mensajes();
            ms.setDestinatario(receptor);
            model.getMessages().add(ms);
        }else{
            for (int i = 0; i < model.getMessages().size(); i++) {
                if(model.getMessages().get(i).getDestinatario()==receptor){
                    bandera = true;
                }
            }
        }
        if(!bandera){
            Mensajes ms = new Mensajes();
            ms.setDestinatario(receptor);
            model.getMessages().add(ms);
        }
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void bodyPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_bodyPanelComponentShown
        
        String matris [][] = new String[ServiceUsuariosContactos.instance().getContactos().size()][2];
        for(int i =0;i<ServiceUsuariosContactos.instance().getContactos().size();i++){
            matris[i][0]=ServiceUsuariosContactos.instance().getContactos().get(i).getNombre();
            matris[i][1]=ServiceUsuariosContactos.instance().getContactos().get(i).getId();
        }
         Contactos.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Nombre", "ID"
            }
        ));
    }//GEN-LAST:event_bodyPanelComponentShown

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        if(this.textBuscar.getText().isEmpty())return;
        List<Contacto> listAux = ServiceUsuariosContactos.instance().buscar2(this.textBuscar.getText());
        String matris [][] = new String[ServiceUsuariosContactos.instance().getContactos().size()][2];
        for(int i =0;i<listAux.size();i++){
            matris[i][0]=listAux.get(i).getNombre();
            matris[i][1]=listAux.get(i).getId();
        }
         Contactos.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Nombre", "ID"
            }
        ));
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefreshActionPerformed
        String matris [][] = new String[ServiceUsuariosContactos.instance().getContactos().size()][2];
        for(int i =0;i<ServiceUsuariosContactos.instance().getContactos().size();i++){
            matris[i][0]=ServiceUsuariosContactos.instance().getContactos().get(i).getNombre();
            matris[i][1]=ServiceUsuariosContactos.instance().getContactos().get(i).getId();
        }
         Contactos.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Nombre", "ID"
            }
        ));
    }//GEN-LAST:event_botonRefreshActionPerformed

    private void ContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactosMouseClicked
        int pos =Contactos.getSelectedRow();
        boolean bandera = false;
        receptor=ServiceUsuariosContactos.instance().getContactos().get(pos).getId();
        this.Destinatario.setText(ServiceUsuariosContactos.instance().getContactos().get(pos).getNombre()+" "+receptor);
        if(this.model.getMessages()==null){
            Mensajes ms = new Mensajes();
            ms.setDestinatario(receptor);
            model.getMessages().add(ms);
        }else{
            for (int i = 0; i < model.getMessages().size(); i++) {
                if(model.getMessages().get(i).getDestinatario()==receptor){
                    bandera = true;
                }
            }
        }
        if(!bandera){
            Mensajes ms = new Mensajes();
            ms.setDestinatario(receptor);
            model.getMessages().add(ms);
        }
        String msg="";
        List<Mensajes> listAux =model.getMessages();
            String m = "";
            for (int i = 0; i <listAux.size(); i++) {
               if(listAux.get(i).getDestinatario()==receptor){
                    for (int j = 0; j < listAux.get(i).getMensajes().size(); j++) {
                        m = listAux.get(i).getMensajes().get(j);
                        msg+=(m +"\n");
                    }
                }
            }
            this.messages.setText(msg);
            this.mensaje.setText("");
            this.mensaje.requestFocus();
    }//GEN-LAST:event_ContactosMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonInsertar;
    private javax.swing.JTable Contactos;
    private javax.swing.JLabel Destinatario;
    private javax.swing.JPanel PanelInsercion;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonRefresh;
    public javax.swing.JPasswordField clave;
    private javax.swing.JButton finish;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton login;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logout;
    public javax.swing.JTextField mensaje;
    private java.awt.TextArea messages;
    public javax.swing.JButton post;
    private javax.swing.ButtonGroup sexoFld;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
    Controller controller;
    Model model;
    
    public void setController(Controller controller){
        this.controller=controller;
    }
    public void setModel(Model model){
        this.model=model;
         model.addObserver(this);
    }
    
    
   public void update(java.util.Observable updatedModel,Object parametros){
       if(model.getCurrentUser()==null){
           loginPanel.setVisible(true);
           bodyPanel.setVisible(false);
           this.PanelInsercion.setVisible(false);
       }
       else{
            loginPanel.setVisible(false);
            bodyPanel.setVisible(true);
            if(this.model.getCurrentUser().conect==true){
                this.setTitle(model.getCurrentUser().getNombre()+" ID:" +model.getCurrentUser().getId()+
                        " Conectado");
            }else{
                this.setTitle(model.getCurrentUser().getNombre()+" ID:" +model.getCurrentUser().getId()+
                        " Desconectado");
            }
            String msg="";
//            for( String m: model.getMessages()){
//                msg+=(m +"\n");
//            }
            List<Mensajes> listAux =model.getMessages();
            String m = "";
            for (int i = 0; i <listAux.size(); i++) {
               if(listAux.get(i).getDestinatario()==receptor){
                    for (int j = 0; j < listAux.get(i).getMensajes().size(); j++) {
                        m = listAux.get(i).getMensajes().get(j);
                        msg+=(m +"\n");
                    }
                }
            }
            this.messages.setText(msg);
            this.mensaje.setText("");
            this.mensaje.requestFocus();
            
        }
        this.validate();
    } 
}
